---
- name: clone git repository to roles directory
  hosts: localhost
  gather_facts: no
  tasks:
   - name: ensure roles directory exist
     file:
          path: "roles"
          state: directory

   - name: clone the git reposotory into the roles directory
     git:
       repo: 'git@github.com:seeegan/Ansible-Roles.git'
       dest: "roles"
       version: master
       force: yes 
